# Generated by Django 3.0.3 on 2020-09-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouterDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=200)),
                ('sapid', models.CharField(max_length=200)),
                ('loopbackid', models.CharField(max_length=200)),
                ('ipv4', models.CharField(max_length=200)),
                ('mac_address', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'router_details',
            },
        ),
    ]
