# Generated by Django 3.0.6 on 2021-06-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerapp1', '0002_routerdetails_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerdetails',
            name='payload',
            field=models.TextField(blank=True),
        ),
    ]
