# Generated by Django 3.0.6 on 2021-06-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routerapp1', '0003_auto_20210609_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routerdetails',
            name='ipv4',
        ),
        migrations.RemoveField(
            model_name='routerdetails',
            name='loopbackid',
        ),
        migrations.RemoveField(
            model_name='routerdetails',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='routerdetails',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='routerdetails',
            name='sapid',
        ),
        migrations.RemoveField(
            model_name='routerdetails',
            name='status',
        ),
    ]
